export const EXPECTED_SCHEMA = {
  chains: [
    'id',
    'name',
    'parent_id',
    'type',
    'sort_order',
    'trigger',
    'duration',
    'description',
    'current_streak',
    'auxiliary_streak',
    'total_completions',
    'total_failures',
    'auxiliary_failures',
    'exceptions',
    'auxiliary_exceptions',
    'auxiliary_signal',
    'auxiliary_duration',
    'auxiliary_completion_trigger',
    'created_at',
    'last_completed_at',
    'user_id',
    'is_durationless',
    'time_limit_hours',
    'time_limit_exceptions',
    'group_started_at',
    'group_expires_at',
    'deleted_at',
  ],
  scheduled_sessions: [
    'id',
    'chain_id',
    'scheduled_at',
    'expires_at',
    'auxiliary_signal',
    'user_id',
  ],
  active_sessions: [
    'id',
    'chain_id',
    'started_at',
    'duration',
    'is_paused',
    'paused_at',
    'total_paused_time',
    'user_id',
  ],
  completion_history: [
    'id',
    'chain_id',
    'completed_at',
    'duration',
    'was_successful',
    'reason_for_failure',
    'user_id',
  ],
  rsip_nodes: [
    'id',
    'user_id',
    'parent_id',
    'title',
    'rule',
    'sort_order',
    'use_timer',
    'timer_minutes',
    'created_at',
  ],
  rsip_meta: ['user_id', 'last_added_at', 'allow_multiple_per_day'],
};
