\n\n-- Create chains table\nCREATE TABLE IF NOT EXISTS chains (\n  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),\n  name text NOT NULL,\n  trigger text NOT NULL,\n  duration integer NOT NULL DEFAULT 45,\n  description text NOT NULL,\n  current_streak integer NOT NULL DEFAULT 0,\n  auxiliary_streak integer NOT NULL DEFAULT 0,\n  total_completions integer NOT NULL DEFAULT 0,\n  total_failures integer NOT NULL DEFAULT 0,\n  auxiliary_failures integer NOT NULL DEFAULT 0,\n  exceptions jsonb NOT NULL DEFAULT '[]'::jsonb,\n  auxiliary_exceptions jsonb NOT NULL DEFAULT '[]'::jsonb,\n  auxiliary_signal text NOT NULL,\n  auxiliary_duration integer NOT NULL DEFAULT 15,\n  auxiliary_completion_trigger text NOT NULL,\n  created_at timestamptz DEFAULT now(),\n  last_completed_at timestamptz,\n  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL\n);
\n\n-- Create scheduled_sessions table\nCREATE TABLE IF NOT EXISTS scheduled_sessions (\n  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),\n  chain_id uuid REFERENCES chains(id) ON DELETE CASCADE NOT NULL,\n  scheduled_at timestamptz NOT NULL DEFAULT now(),\n  expires_at timestamptz NOT NULL,\n  auxiliary_signal text NOT NULL,\n  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL\n);
\n\n-- Create active_sessions table\nCREATE TABLE IF NOT EXISTS active_sessions (\n  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),\n  chain_id uuid REFERENCES chains(id) ON DELETE CASCADE NOT NULL,\n  started_at timestamptz NOT NULL DEFAULT now(),\n  duration integer NOT NULL,\n  is_paused boolean NOT NULL DEFAULT false,\n  paused_at timestamptz,\n  total_paused_time integer NOT NULL DEFAULT 0,\n  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL\n);
\n\n-- Create completion_history table\nCREATE TABLE IF NOT EXISTS completion_history (\n  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),\n  chain_id uuid REFERENCES chains(id) ON DELETE CASCADE NOT NULL,\n  completed_at timestamptz NOT NULL DEFAULT now(),\n  duration integer NOT NULL,\n  was_successful boolean NOT NULL,\n  reason_for_failure text,\n  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL\n);
\n\n-- Enable Row Level Security\nALTER TABLE chains ENABLE ROW LEVEL SECURITY;
\nALTER TABLE scheduled_sessions ENABLE ROW LEVEL SECURITY;
\nALTER TABLE active_sessions ENABLE ROW LEVEL SECURITY;
\nALTER TABLE completion_history ENABLE ROW LEVEL SECURITY;
\n\n-- Create RLS policies for chains\nCREATE POLICY "Users can manage their own chains"\n  ON chains\n  FOR ALL\n  TO authenticated\n  USING (auth.uid() = user_id)\n  WITH CHECK (auth.uid() = user_id);
\n\n-- Create RLS policies for scheduled_sessions\nCREATE POLICY "Users can manage their own scheduled sessions"\n  ON scheduled_sessions\n  FOR ALL\n  TO authenticated\n  USING (auth.uid() = user_id)\n  WITH CHECK (auth.uid() = user_id);
\n\n-- Create RLS policies for active_sessions\nCREATE POLICY "Users can manage their own active sessions"\n  ON active_sessions\n  FOR ALL\n  TO authenticated\n  USING (auth.uid() = user_id)\n  WITH CHECK (auth.uid() = user_id);
\n\n-- Create RLS policies for completion_history\nCREATE POLICY "Users can manage their own completion history"\n  ON completion_history\n  FOR ALL\n  TO authenticated\n  USING (auth.uid() = user_id)\n  WITH CHECK (auth.uid() = user_id);
\n\n-- Create indexes for better performance\nCREATE INDEX IF NOT EXISTS idx_chains_user_id ON chains(user_id);
\nCREATE INDEX IF NOT EXISTS idx_chains_created_at ON chains(created_at DESC);
\nCREATE INDEX IF NOT EXISTS idx_scheduled_sessions_user_id ON scheduled_sessions(user_id);
\nCREATE INDEX IF NOT EXISTS idx_scheduled_sessions_expires_at ON scheduled_sessions(expires_at);
\nCREATE INDEX IF NOT EXISTS idx_active_sessions_user_id ON active_sessions(user_id);
\nCREATE INDEX IF NOT EXISTS idx_completion_history_user_id ON completion_history(user_id);
\nCREATE INDEX IF NOT EXISTS idx_completion_history_chain_id ON completion_history(chain_id);
\nCREATE INDEX IF NOT EXISTS idx_completion_history_completed_at ON completion_history(completed_at DESC);
;
